services:
  rust-observability:
    build: .
    container_name: rust-observability
    ports:
      - "8080:8080"
    environment:
      - RUST_OBSERVABILITY_VMS=1
      - RUST_LOG=info
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.7
    container_name: loki
    command: ["-config.file=/etc/loki/config/loki-config.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/config/loki-config.yml:ro
      - loki_data:/loki
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.7
    container_name: promtail
    command: ["-config.file=/etc/promtail/config/promtail-config.yml"]
    volumes:
      - ./loki/promtail-config.yml:/etc/promtail/config/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
    depends_on:
      - rust-observability
      - promtail
      - loki
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      # Use a more secure password in production
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring

volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}

networks:
  monitoring:
    driver: bridge