global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rust-observability'
    metrics_path: /metrics
    static_configs:
      - targets: ['rust-observability:8080']