{
 "title": "DEMO-APP",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_filter", "label": "App log filter (content)", "query": "rust-observability" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rust_observability_process_cpu_usage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rust_observability_process_memory_virtual_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"DOCKER_COMPOSE\"} |= `application=${app_filter}` != `org_id=fake` != `luginId=loki` != `MeterProvider.GlobalSet`"
    }
   ]
  }
 ]
}